language: node_js
node_js:
  - v5
  - v4
  - '0.12'
  - '0.10'
before_install:
  - 'npm install codecov.io'
before_script:
  - 'npm run lint'
script:
  - 'npm run build'
after_script:
  - 'npm run codecov'
